---
abstract: "Perl extension wrapping OpenDMARC's libopendmarc library"
author:
  - 'Davide Migliavacca <shari@cpan.org>'
build_requires:
  File::ShareDir::Install: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-DMARC-opendmarc
no_index:
  directory:
    - t
    - inc
requires:
  File::ShareDir: 0
version: 0.10
