--- #YAML:1.0
name:               Mail-DMARC-opendmarc
version:            0.11
abstract:           Perl extension wrapping OpenDMARC's libopendmarc library
author:
    - Davide Migliavacca <shari@cpan.org>
license:
    - artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::ShareDir::Install:  0
requires:
    File::ShareDir:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
release_status:     unstable
