package Mail::DMARC::opendmarc::Constants::C::Symbols;

use 5.008003;
use strict;
use warnings;

use base 'Exporter';

our @EXPORT = qw( @ALL );

our @ALL = qw(
    DMARC_DNS_ERROR_NO_RECORD
    DMARC_DNS_ERROR_NXDOMAIN
    DMARC_DNS_ERROR_TMPERR
    DMARC_FROM_DOMAIN_ABSENT
    DMARC_MAXHOSTNAMELEN
    DMARC_PARSE_ERROR_BAD_DKIM_MACRO
    DMARC_PARSE_ERROR_BAD_SPF_MACRO
    DMARC_PARSE_ERROR_BAD_VALUE
    DMARC_PARSE_ERROR_BAD_VERSION
    DMARC_PARSE_ERROR_EMPTY
    DMARC_PARSE_ERROR_NO_ALLOC
    DMARC_PARSE_ERROR_NO_DOMAIN
    DMARC_PARSE_ERROR_NO_REQUIRED_P
    DMARC_PARSE_ERROR_NULL_CTX
    DMARC_PARSE_OKAY
    DMARC_POLICY_ABSENT
    DMARC_POLICY_DKIM_ALIGNMENT_FAIL
    DMARC_POLICY_DKIM_ALIGNMENT_PASS
    DMARC_POLICY_DKIM_OUTCOME_FAIL
    DMARC_POLICY_DKIM_OUTCOME_NONE
    DMARC_POLICY_DKIM_OUTCOME_PASS
    DMARC_POLICY_DKIM_OUTCOME_TMPFAIL
    DMARC_POLICY_IP_TYPE_IPV4
    DMARC_POLICY_IP_TYPE_IPV6
    DMARC_POLICY_NONE
    DMARC_POLICY_PASS
    DMARC_POLICY_QUARANTINE
    DMARC_POLICY_REJECT
    DMARC_POLICY_SPF_ALIGNMENT_FAIL
    DMARC_POLICY_SPF_ALIGNMENT_PASS
    DMARC_POLICY_SPF_ORIGIN_HELO
    DMARC_POLICY_SPF_ORIGIN_MAILFROM
    DMARC_POLICY_SPF_OUTCOME_FAIL
    DMARC_POLICY_SPF_OUTCOME_NONE
    DMARC_POLICY_SPF_OUTCOME_PASS
    DMARC_POLICY_SPF_OUTCOME_TMPFAIL
    DMARC_RECORD_A_RELAXED
    DMARC_RECORD_A_STRICT
    DMARC_RECORD_A_UNSPECIFIED
    DMARC_RECORD_P_NONE
    DMARC_RECORD_P_QUARANTINE
    DMARC_RECORD_P_REJECT
    DMARC_RECORD_P_UNSPECIFIED
    DMARC_RECORD_RF_AFRF
    DMARC_RECORD_RF_IODEF
    DMARC_RECORD_RF_UNSPECIFIED
    DMARC_TLD_ERROR_UNKNOWN
    OPENDMARC_LIB_VERSION
    OPENDMARC_MAX_NSADDRLIST
    OPENDMARC_TLD_TYPE_MOZILLA
    OPENDMARC_TLD_TYPE_NONE
);

1;
